services:
    anime_db.ani_db.search:
        class: AnimeDb\Bundle\AniDbFillerBundle\Service\Search
        arguments: [ @anime_db.ani_db.browser, %anime_db.ani_db.titles_db%, %kernel.cache_dir%, %locale% ]
        tags:
            - { name: anime_db.search }
        calls:
            - [setRouter, ['@router']]
            - [setFiller, ['@anime_db.ani_db.filler']]

    anime_db.ani_db.filler:
        class: AnimeDb\Bundle\AniDbFillerBundle\Service\Filler
        arguments: [ @anime_db.ani_db.browser, @doctrine, @anime_db.downloader, %locale% ]
        tags:
            - { name: anime_db.filler }
        calls:
            - [setRouter, ['@router']]

    anime_db.ani_db.refiller:
        class: AnimeDb\Bundle\AniDbFillerBundle\Service\Refiller
        arguments: [ @anime_db.ani_db.browser, @anime_db.ani_db.filler, @anime_db.ani_db.search ]
        tags:
            - { name: anime_db.refiller }

    anime_db.ani_db.listener.console:
        class: AnimeDb\Bundle\AniDbFillerBundle\Event\Listener\Console
        arguments: [ %kernel.root_dir% ]
        tags:
            - { name: kernel.event_listener, event: console.terminate, method: onTerminate }

    anime_db.ani_db.listener.refiller:
        class: AnimeDb\Bundle\AniDbFillerBundle\Event\Listener\Refiller
        arguments: [ @event_dispatcher, @anime_db.ani_db.refiller, @anime_db.ani_db.filler ]
        tags:
            - { name: kernel.event_listener, event: anime_db.storage.add_new_item, method: onAddNewItem }
