services:
    anime_db.ani_db.search:
        class: AnimeDb\Bundle\AniDbFillerBundle\Service\Search
        arguments: [ @anime_db.ani_db.browser, %anime_db.ani_db.import_titles%, %kernel.cache_dir%, %locale% ]
        tags:
            - { name: anime_db.search }
        calls:
            - [setRouter, ['@router']]
#            - [setFiller, ['@anime_db.ani_db.filler']]